version: '3'

services:
  cassandra-db:
    image: cassandra:latest
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=10.42.42.42
    ports:
      - 9042:9042
    volumes:
      - cassandra_volume:/var/lib/cassandra
    mem_limit: 5g

volumes:
  cassandra_volume: